### ISSUE TITLE
Minor typos on page /04-package-structure.html

### ISSUE THREAD

**Issue by eliasdabbas** [py-pkgs/py-pkgs#104]
"the poetry-core library is require**d** to build our package"

It seems a "d" is missing from the word "required". 

Also, the link  "**the poetry module poetry-core’s poetry.core.masonry.api module**" leads to a 404 page:

https://github.com/python-poetry/poetry-core/blob/master/poetry/core/masonry/api.py

I believe this is the right URL:

https://github.com/python-poetry/poetry-core/blob/master/src/poetry/core/masonry/api.py

**Comment by TomasBeuzen** [comment]
Thanks for taking the time to let us know @eliasdabbas!! Fixes merged 😄
