### ISSUE TITLE
THANKS for having written this amazing book!

### ISSUE THREAD

**Issue by ubaldot** [py-pkgs/py-pkgs#123]
I just want to say THANKS for this book that was like a compass in the complete open and wild ocean of packaging tools, setups, folder structures, __init__ files and so on and so forth.
I wish I could have discovered it before, it would have saved me thousands of hours,headaches and hairs ahahah

Thanks again and keep up the good work! 

/U.

**Comment by TomasBeuzen** [comment]
Thanks very much for the kind words @ubaldot - we appreciate you taking the time to write them out, means a lot to us! Happy packaging 😄
