### ISSUE TITLE
Name change: "Remote - Containers" is now called "Dev Containers"

### ISSUE THREAD

**Issue by cosimameyer** [py-pkgs/py-pkgs#124]
Thanks so much for writing the book - it's an excellent resource with an intuitive guideline! I believe that the extension "Remote - Containers" (described in section 2.6.1. Docker with Visual Studio Code) is now called ["Dev Containers"](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers).

**Comment by TomasBeuzen** [comment]
Thanks for the kind words @cosimameyer - and you are absolutely right about that! (I use Dev Containers every day and didn't even notice the name change!). Happy packaging 😄
