### ISSUE TITLE
Search seems to be broken...

### ISSUE THREAD

**Issue by Bernmeister** [py-pkgs/py-pkgs#132]
Using the search (magnifying glass and ``CTRL+K``) within the book, no results come up.  For example, I searched for "poetry" and got no results (and no results for other text which _should_ be there).  Have tried this on both Chromium and Firefox (Ubuntu 20.04).

**Comment by TomasBeuzen** [comment]
Thanks very much for the heads up on this @Bernmeister - have pushed a fix 😄 Appreciate you taking the time to let us know!
