### ISSUE TITLE
Chapter 9 - Python Packaging Cheatsheet

### ISSUE THREAD

**Issue by TomasBeuzen** [py-pkgs/py-pkgs#15]
I've been developing some packages lately and have found myself going over this book searching for particular commands I know I want to use. As someone who understands what's going on and only needs the commands to execute certain tasks, I think a "cheatsheet" would be really helpful (maybe as an appendix or preface?). I envision a very simply document showing the step-by-step commands for creating a package, but without much (if any) documentation, e.g.:

**Package Set Up**
1. Create directory structure: `cookiecutter https://github.com/UBC-MDS/cookiecutter-ubc-mds.git`
2. Initialize poetry: `cd pkg-name` & `poetry init`
etc

**Package Buidling/Testing**
1. Add dependencies: `poetry add numpy`
2. Add dev dependencies: `poetry add --dev sphinx`
3. Lock dependency list/install dependencies/install package locally: `poetry install`
etc

**Documentation**
1. Modify contents of `docs`
2. Download napoleon: `poetry add --dev sphinxcontrib-napoleon`
3. Render code documentation with `poetry run sphinx-apidoc -f -o docs/source foocat`
4. Render package documentation: `cd docs`, then `poetry run make html`
etc

**Comment by ttimbers** [comment]
I like this idea, I kind of have this in the quickstart in the MDS Cookiecutter repo README (see [this](https://github.com/UBC-MDS/cookiecutter-ubc-mds#quickstart)). However, what you outline is simpler... Should we model this to be as aesthetically pleasing as the RStudio cheatsheets? Also, would this be a standalone doc, or part of the book?

**Comment by TomasBeuzen** [comment]
Ah yes like that but even simpler (if possible)!

I envision it being an appendix in the book. But I do really like the the RStudio cheatsheets and I think shipping it as a standalone document would be cool too. I'll think more on this once we have a few more of the final chapters added.

**Comment by TomasBeuzen** [comment]
[Here's a first draft](https://ubc-mds.github.io/py-pkgs/content/09-cheatsheet.html). It is currently embedded as a .png image with links to the pdf version for download on GitHub. I might convert it to html to embed directly in the webpage but I'll see how easy it is to do...

**Comment by ttimbers** [comment]
Its so pretty! 😍

**Comment by ttimbers** [comment]
Where does this live now? And is it in any of the book chapters?

**Comment by TomasBeuzen** [comment]
It lives as an appendix for now: https://py-pkgs.org/a2-cheatsheet

(raw pdf available in the repo [here](https://github.com/UBC-MDS/py-pkgs/tree/master/py-pkgs/images/raw))

**Comment by ttimbers** [comment]
Thanks!
