### ISSUE TITLE
Proposal: add section on fixtures to testing chapter

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#45]
@TomasBeuzen - I think fixtures are a really nice idea and feature for testing in Python for data science. It would be nice to add a section on this to our testing chapter. Here are some examples of MDS students using fixtures in their data science projects last year:

1. https://github.com/UBC-MDS/PyDataPeek/blob/master/tests/test_sample_data.py#L25
2. https://github.com/UBC-MDS/pylaundry/blob/master/tests/test_select_features.py

**Comment by ttimbers** [comment]
Here's a dead simple explanation and example: https://www.tutorialspoint.com/pytest/pytest_fixtures.htm

Another thing that is nice about fixtures is the ability to parameterize them. See these docs: https://docs.pytest.org/en/stable/parametrize.html

**Comment by TomasBeuzen** [comment]
We do have fixtures in the book already here: https://py-pkgs.org/05-testing#fixtures

But I'd like to expand that section a little bit and show some more examples!

**Comment by ttimbers** [comment]
Whoops! 😳  

I somehow skipped over this one! 

In the context of data science, I think there are at least 2-3 things we might want to add and expand on:
1. Placing a rationale as to why a fixture function, as opposed to just a function, they are dry as well, right? (from my understanding fixtures return the object, and make it available to whatever tests need them, and this happens once, before the test is run, as opposed to re-running the function for every test that needs the data, which is what would happen without fixtures)
2. Creating other test data (e.g., images)
3. Creating files/directories/etc for functions that read/write data
