### ISSUE TITLE
Changing the book example

### ISSUE THREAD

**Issue by TomasBeuzen** [py-pkgs/py-pkgs#48]
@ttimbers I've been thinking a lot about a potentially different package we could develop through the book that will make it easier to showcase various important elements of the packaging process:
- multiple functions/sub-packages
- functions that create plots/writing tests for viz
- shipping data with the package
- something with multiple dependencies (e.g., numpy, matplotlib, etc)
- etc

One idea I had was to build a package similar to my simple [pyguest](https://github.com/TomasBeuzen/pyguest) package. A package for estimating attendance at an event (like a party or wedding) using simulations of Bernoulli RVs and probabilities stored in a dataframe. It's simple, easy to describe, easy to expand (e.g., add functionality to also simulate if +1's will come), we could ship example data with it, we could have plotting function (e.g., histogram of simulation outcomes). Also the name `partypy` is currently available on pypi 😆  Let me know what you think. I can always whip up a quick draft of what Chapter 3 How to package a Python might look like with this revised package.

**Comment by ttimbers** [comment]
Cool, I like it. Let's do it. What would the data look like coming out of it. I need to work on a test example for altair viz... This could be my example...

**Comment by ttimbers** [comment]
Something like this SE post: https://stats.stackexchange.com/questions/486294/estimate-number-of-party-guests ?

**Comment by ttimbers** [comment]
Would also be neat to be able to add different probabilities for different groups of guests? Like local vs remote wedding guests?

**Comment by ttimbers** [comment]
Here's a real rough prototype: https://github.com/UBC-MDS/partypy-prototype/blob/main/scripts/prototype.ipynb

Of course the altair chart does not render on GitHub, so I paste it here: 
<img width="566" alt="Screen Shot 2021-03-02 at 10 36 19 PM" src="https://user-images.githubusercontent.com/6865016/109763978-c46a7c80-7ba7-11eb-9691-f01217d39c18.png">


Please feel free to say yes/no, enhance, edit, etc.

**Comment by TomasBeuzen** [comment]
Yep - this is pretty similar to what I had in mind (I have a similar workflow/plot in a post on [my website](https://www.tomasbeuzen.com/post/party-planning-probability/)).

We can do so much extra here, but for example, you mentioned different groups of guests. We could add a `groupby` argument like:

```python
def attendance(p, guests, groupby=None):
    """
```

Which would group guests by some attribute (remote/in-person, adult/child, gender, etc.). If that argument is specified the returned dataframe might look like:

|simulation|total_simulated_guests|remote_simulated_guests|in-person_simulated_guests|
|---|---|---|---|
|0|31|15|16
|1|25|20|5|
|2|27|19|8|
|...|...|...|...|

That additional argument could come later in the book when we introduce versioning and add functionality to our package. I think for Chapter 3, what you have in the notebook covers the scope nicely! I can work on re-drafting Chapter 3 to include this updated code. Thanks for working on this - I'm very excited about it :D

**Comment by ttimbers** [comment]
Are you OK with me simulating the number of guests instead of the probability? I think what the user might care about more is the number, and the possible ranges (i.e., confidence intervals).

**Comment by ttimbers** [comment]
Also, I think the ci function should have another argument to take in confidence level, maybe someone wants 99% ci's, or 80%, etc.

**Comment by TomasBeuzen** [comment]
Yep to both!
