### ISSUE TITLE
Chapter 3 - Package structure and state

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#7]

**Comment by ttimbers** [comment]
@tomasbeuzen has kindly offered to draft this chapter. @tomasbeuzen, once you have started please move this issue on the [Book Chapter project board](https://github.com/UBC-MDS/py-pkgs/projects/1) from Ideology to Draft.

**Comment by TomasBeuzen** [comment]
Started. Have uploaded a draft framework of the chapter and have moved to "draft" on the project board.

**Comment by TomasBeuzen** [comment]
@ttimbers this chapter is ready for review and has been moved to "Proofs" on the project board.

**Comment by ttimbers** [comment]
Starting to get on board with your organization and putting feedback here instead of creating a new issue 😅 

- We should better explain the `import` variants we demo in the code chunk below. For example, one might ask how is line one different from line 4? And how would we access `list_range` when using the `from simple_math import list_range ` syntax? I know this is skirting the issue that we are not teaching Python, but I think this is close enough to packaging we should make it clear and explicit.
 
  ```
  import simple_math  # imports the entire module. Functions can then be accessed via dot notation, e.g., simple_math.list_range()
  from simple_math import list_range  # import only list_range function
  from simple_math import odd_even  # import only odd_even function
  from simple_math import *  # import all functions
  ``` 

- Let's please not suggest folks share code via email/Slack here (i.e., edit "Because modules are single files they can easily be shared to others by e.g., email, GitHub, Slack, etc. ")

- I think we need to provide some justification as to why you would ever have nested packages, we know why, but I think we need to tell the novice reader.

- I think another justification for packaging is to avoid copy and paste errors when reusing a module between projects in your own work. Also, forgetting to copy paste, and then realizing the module isn't there because you didn't copy it to the new project's directory after some debugging 😱 . Here is where I have written a couple sentences on this, feel free to borrow/riff if you think it makes sense: https://pages.github.ubc.ca/MDS-2020-21/DSCI_524_collab-sw-dev_students/materials/lectures/01_lecture-intro-to-r-and-python-pkgs.html#when-to-start-writing-an-r-or-python-package

-  In the note about that we prefer to use poetry as opposed to setup tools, I think we can better justify why we are even talking about `setuptools`... Because it is still so widely used (because `pyproject.toml` is still pretty young - PEP 518 was only made in 2016), they may very likely encounter it and should know about it. **Addendum:** I see you later mention this... hmmm... might be better to move this all upfront for this section to provide clear rationale and justification. Also, maybe a sentence or two on why not `setuptools`? 

- I think we need to define "source", "built" and "binary", we use the terms freely without explaining them. Ah, again, I see you do this later ("Binary distribution packages are simply packages that contains pre-compiled extensions - as an analogy, you can think of your source code as a cake recipe, while a binary distribution is the fully cooked cake."), I think it should come earlier. 

- This is unclear: "Pure Python wheels: pure Python but don’t support both Python 2 and 3", there is something off with the grammar, and what does it support?

**Comment by ttimbers** [comment]
- How modified/derived are the circle diagrams in this chapter? If they at all resemble those from the source you attribute, we might need some formal permission for publication in print.

- Let's lose the CL (command line acronym)

- perhaps we should define namespace here, many users of Python use the language without formally knowing what a namespace is (once you explain it, they realize they have an idea/concept for it, just not a name for it)

- I find figure 4.3 confusing...
