### ISSUE TITLE
Introduction feedback

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#70]
- [x] Can we qualify what the `numpy` package is the first time we use it (a Python package for doing numerical operations with arrays) and cite it?
- [x] Let's be careful to not say things like "just do this" or "as simple as" (for example, the last sentence in the first paragraph of the introduction does this). It is demotivating to learners who might not find, or have at one point found, that simple. I see this use of "simple" other places in this chapter too. And simply... You really like that phrasing 😉 
- [x] I think we should be clearer in the introduction that we expect reader to know how to import packages and know what a package alias is.
- [x] "At some point, all of us have wanted to reuse code from one project in another" > this may not be true for all readers, how about: "At some point after programming for a while, most people will reach a point where they want to reuse code from one project in another"
- [x] "reprehensible" is a bit of an unkind word, especially in the context it is being used towards new learners, doing something that seems reasonable to them because they have not yet been shown a better way... could we use the phrase "error-prone" or something like that? I guess what I don't like about "reprehensible" is that its definition involves blame and reproach, things novices are not really deserving of for not knowing better.
- [x] Along the same lines, could we remove "obviously" from  "obviously inefficient". Again, it might not be obvious to our learners yet...
- [x] Fig 1.1 is not referenced in the text. If it's there, we should say something about it and reference it.
- [x] In the "Why you should create packages" section above, we start with "As discussed above, ..." however, some things were not really discussed above. For example, isolating dependencies, reproducibility (this was at least not defined), bundle up reproducible data analysis. 
- [x] Here you refer to the terminal, but in the next chapter you take time to discuss terminal versus command-line interface, and opt to use CLI... We should be consistent with the choice of language between these two chapters.

**Comment by TomasBeuzen** [comment]
A few notes related to the above for future reference:
- I'll use "CLI" and "command line" as preferred language over "terminal"
- All the syntactic and grammatical comments I fully agree with and have addressed
