### ISSUE TITLE
System setup feedback

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#71]
- [x] Here you write "Installing all the packages you need in the same place (i.e., the system default location) can be problematic because different packages have different dependencies," but it's not the extra packages/deps that is the issue, its that they require different versions of the same package... We should be clear about that.
- [x] In the first note we write "If you know what you’re doing, ..." that is a bit condescending and implies readers who are using conda, or other things don't know what they are doing. Can we just say another common way to install this is using pip - however unless you take charge of your environments using some other method, you could run into the issues we described above? (which isn't wholly true, as Poetry will also create a virtual environment if conda isn't used...).
- [x] In Happy Git with R, Jenny has a section called "Git already installed?" (https://happygitwithr.com/install-git.html#git-already-installed), wondering if we want something similar for conda? Not sure, so I will let you choose.
- [x] How are we going to deal with links in the print version? Like TestPyPI and PyPI? Should they be footnotes? We should ask CRC, or maybe there's a hint in some style guide they shared with us?
- [x] Oh boy, we do require them to know Git and GitHub, like we are not teaching them this... So... we should make that clear in the preface, where we write our expectation of Python knowledge, and point folks to some reasonable resources if they are not familiar, perhaps? We will want to do that again in the chapters where we use and discuss version control. We wrote a very gentle intro to git & GitHub here, but it relies on Jupyter lab... which might be fine for this audience? Take a look and decide: https://ubc-dsci.github.io/introduction-to-datascience/Getting-started-with-version-control.html . Looking at the R packages book, they have a chapter on Git and GitHub: https://r-pkgs.org/git.html . If we decide to do this, we might want to take a more opinionated stance on the IDE in this chapter, or decide to write that section using the Git CLI instead of the JupyterLab or VScode Git GUI?
- [x] Also this isn't quite accurate: "A version control system works by storing a master copy of your project in a “repository” which you don’t edit directly. Instead, you edit a copy of the project file(s), and then commit changes back to the repository. " ... But I am not sure that we want to get more detailed/complicated here... So perhaps remove that and add "over the lifespan of a project." to the sentence before it?
- [x] In the "Install Git and register for a GitHub account" section we write "master copy" we should change the language to "main copy".
- [x] If we are going to recommend 7 VSCode extensions, we should explain what they are for and why people should use them. Do you think we really need to recommend all 7? Can we pare that number down a little bit?
- [x] For RStudio, do we want to be more explicit about the version of RStudio? The object explorer for Python only became available in 1.4 (I think?)...
- [x] I am not a fan of the "Collaborative package development and packaging in the cloud" section. Mostly because it's complicated... Second, because what is currently written is not correct, at least the JuputerHub bit (there you still need Git + GitHub to collaborate unless you use the new Jupyter Lab real time collaboration - and I think it uses Binder, so JHub is not needed???) I think we need > 1 paragraph to do it justice... In particular, I think a conversation of the downsides of these approaches is warranted when proposing them... So as cool as they are, I think we don't have enough experience using them, and how to use them well to recommend? You can try to convince me otherwise, happy to discuss further.

**Comment by TomasBeuzen** [comment]
Some notes on these comments:
- Various grammatical/syntax suggestions implemented
- Removed "Collaborative package development" section
- Added guidance on RStudio version
- Narrowed down VS Code extension list and provided descriptions
- Simplified and corrected description of version control. 
- I've added a new section "Assumptions" to the preface of the book which assumes readers have basic familiarity with importing packages, writing functions, using git and github (or equivalent). There are so many excellent descriptions of how and why to use git in other books, I don't really want to provide just another version (but perhaps we will have to, I'm not against it). I've linked to some resources and have added a note again in system setup that we assume basic familiarity (we really are only using the absolute basics, `add`, `commit`, `push`)
- Links will be provided as footnotes :) (luckily this is already taken care of by the LaTeX style file provided to us)
