### ISSUE TITLE
Chapter 4 - Testing

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#8]
We need to write a chapter on testing using pytest. This chapter does not include the CI parts of testing. That is for a later chapter on CI and other bells and whistles.

**Comment by TomasBeuzen** [comment]
@ttimbers - first draft of this chapter is finished and ready for a review. I've moved it to "Proofs".

**Comment by ttimbers** [comment]
Whoohoo! I'll review this today!

**Comment by ttimbers** [comment]
OK, I think we should add more on coverage. I have a good section here from my lecture notes that explains what coverage is, what is line vs branch. How you can get each from pytest-cov, and how pytest-cov (well coverage really) actually calculates this (it is not well documented anywhere...). Also, let's use branching to demo the html reports, as they are a lot more useful for that. We just copy this over in large part I think?

- https://pages.github.ubc.ca/MDS-2020-21/DSCI_524_collab-sw-dev_students/materials/lectures/04_lecture-debugging-and-docs.html#
