### ISSUE TITLE
Issue on page /01-introduction.html

### ISSUE THREAD

**Issue by benjy765** [py-pkgs/py-pkgs#86]
Hello, there is a small mistake for the following lines of code: 

```{prompt} python >>> auto
>>> import math
>>> np.round(np.pi, decimals=3)
```

The numpy librairy should be imported instead:

```{prompt} python >>> auto
>>> import numpy as np
>>> np.round(np.pi, decimals=3)
```

Thank you!

**Comment by TomasBeuzen** [comment]
Many thanks @benjy765! This one slipped by me 😬 Appreciate you taking the time to make an issue!
