### ISSUE TITLE
Chapter 5 - Documentation

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#9]
We need to write a chapter on documentation. This would encompass what is covered in Object documentation & vignettes chapters of [the R packages book](https://r-pkgs.org).

**Comment by ttimbers** [comment]
@TomasBeuzen : Gotcha for Poetry + Read the Docs is that you need a [.readthedocs.yml](https://github.com/UBC-MDS/cookiecutter-ubc-mds/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.readthedocs.yml) file. The why for this might be able to be parsed from here (where I learned about this solution: https://github.com/readthedocs/readthedocs.org/issues/4912)

**Comment by TomasBeuzen** [comment]
This chapter has been drafted and moved to the proofs section.

**Comment by ttimbers** [comment]
Add a section to explain how to create vignettes using `nbsphinx`. See the docs: https://nbsphinx.readthedocs.io/en/0.7.0/index.html
