### ISSUE TITLE
Issue on page /03-how-to-package-a-python.html

### ISSUE THREAD

**Issue by mtkerbeR** [py-pkgs/py-pkgs#94]
Thanks for the great work - really very helpful to get up to speed in Python with some background in R.

Two minor points:

1. _we can now build our documentation with sphinx using the following command from our root package directory_
This did not work for me (on Windows) from the _root directory_, but from directory _docs_.

2. At some points in the html-document, the string "\newpage" appears.

**Comment by TomasBeuzen** [comment]
Hi @mtkerbeR - thanks for the kind words and thank you very much for raising these two issues! We appreciate you taking the time, it's so helpful to know when things aren't working as expected.

1. Will push a fix for this tonight :)
2. Just pushed a fix for this in #96 (the `\newpage` were Latex commands related to the PDF render of the book we've been working on). Forgot to remove them post-HTML build 🙈

**Comment by TomasBeuzen** [comment]
Hi @mtkerbeR - I just tried to replicate your error with building the docs but couldn't (Windows 10 using Powershell). If you have a chance:

- Could you let me know what shell you were using?
- Was there any error message that you recall?
- To be clear, I would have expected `make html` to only work if you were in the `docs/` folder, but [the book suggests](https://py-pkgs.org/03-how-to-package-a-python#building-documentation) using `make html --directory=docs/` which I'm expecting should work from the package root which contains the `docs/` directory (the `--directory` command tell make to move into the specified directory before doing anything). Which command were you using? If it was the latter and it didn't work it's definitely something I want to fix.

Thanks again, I appreciate your time :)

**Comment by mtkerbeR** [comment]
Thanks for having a look. I think the problem is that file `make.bat` is located in folder `docs`. 
Hence the terminal within Pycharm (probably CMD) cannot find `make` at all in the root directory - translating from German, error message is roughly "cannot find "make - make Sure You Typed the Name Correctly"
