### ISSUE TITLE
add a note or warning about upper caps on dependencies?

### ISSUE THREAD

**Issue by NickleDave** [py-pkgs/py-pkgs#95]
Hi @TomasBeuzen and @ttimbers -- thank you again for this great guide.

I'm wondering if it would be worth adding some sort of callout somewhere, like a note or warning, about putting upper caps on dependencies?

By "upper caps" I mean what you get when you accept the default "caret" operator that `poetry` uses, to mean "This version and any version that is *less* than a 'major' version change under semantic versioning".

As you show here for your "adding dependencies example":
https://github.com/py-pkgs/py-pkgs/blob/eb68c4fcb7b48cf736d064e023aabdea7070dd91/py-pkgs/bookdown/03-how-to-package-a-python.Rmd#L644

and also shown here for Python itself:
https://github.com/py-pkgs/py-pkgs/blob/eb68c4fcb7b48cf736d064e023aabdea7070dd91/py-pkgs/bookdown/03-how-to-package-a-python.Rmd#L492

Guessing you know what I mean but just making sure I'm clear.

The basic issue with this default is that it's "infectious" -- it forces everyone else that depends on your package to meet the same constraints. This means that they can't, e.g., use a newer version of some dependency that fixes a security issue.

By making their caret operator a default, `poetry` promotes this, as does language in their documentation. I think for the `poetry` devs this recommendation makes sense, because they are thinking mainly in terms of deployed applications, and because they think every package should adhere to the strictest interpretation of Semantic Versioning.

But it can have really painful knock-on effects for downstream users, especially relative beginners like me who have no idea why everything is suddenly broken. I have run into issues resulting from accepting that default for my own packages.

The knock-on effects can get pretty nuanced (and I'm not sure I understand them all). 
See these detailed blog posts from @henryiii for more background: 
https://iscinumpy.dev/post/bound-version-constraints/
https://iscinumpy.dev/post/poetry-versions/

Like you all (and @henryiii ) I really like `poetry` because it provides an all-in-one solution, but I'm a bit worried about a lot of people reading your wonderful guide, just accepting the defaults, and then we're all forced to specify `python=>3.8.1 <4.0` and `jedi^0.19` all the time. I really don't want to constantly have to be tracking when all my dependencies release new versions.

Not sure where the best place to insert this kind of language would be, but just thought I'd suggest it so maybe others can avoid my pain 🙂

**Comment by TomasBeuzen** [comment]
Hi @NickleDave! Firstly, a big thank you for taking the time to write this out - we really appreciate the contribution!

I completely hear everything you're saying, and you've convinced me that we need to include a discussion on this topic in the book. We actually had a short section in there on just this some time ago, but found it to be a little confusing/overwhelming for beginners in particular. We need to revisit that section with clearer language and examples. 

As you say, I love that `poetry` tries to abstract the technical details of the packaging process into a user-friendly tool for beginners (and seasoned developers alike). But it can certainly be opinionated on things. It seems like they won't be changing their opinion on this anytime soon so it's worth bringing to people's attention (I also love your use of the word "infectious" - very apt!)

I'll try to write some words on this sometime over the New Year break but we'll keep this issue open in the meantime. Until then, I hope you have a wonderful New Year! 🎉

**Comment by NickleDave** [comment]
👍 

Yes, it is definitely a confusing topic.

I wonder if you could just say in the main text, e.g. in Chapter 3 when you first set a version, "we strongly recommend setting versions this way as we explain in more detail in Chapter x"

Then in Chapter x say "this topic is complicated but basically we recommend not upper capping versions because of reasons 1, 2, 3 (maybe include links to explainer blog posts as foot notes?)"

Also ...
have you looked at `pdm` as an alternative to `poetry`? Henry Schreiner mentions it in his posts.  
Seems like it has many of the same benefits, **and** favors using a PEP 621 `[project]` table instead of declaring metadata in a tool-specific  (and no caret!)  
I'm taking it for a test drive now. 

Hope you have a wonderful New Year as well!

**Comment by TomasBeuzen** [comment]
Hi @NickleDave - happy new year and I hope you're well! 

I've finally gotten around to writing up a section about dependency version constraints, you can [preview the changes here](https://deploy-preview-106--zen-ptolemy-4bba7d.netlify.app/03-how-to-package-a-python#dependency-version-constraints). If you have a chance, I was wondering if you could run an eye over it to see if the text is in line with what you were thinking, and if you think it would have helped you if you did not know about this issue already. Just a simple, e.g.,  "looks good", or "needs a bit more explanation of upper caps" would be great. I still need to fix of the flow/grammar a little bit but the gist of it is there 😄 

ps. I do know about `pdm` but haven't used it in a project yet (`poetry` mostly satisfies my needs). What's your impression after using it?

**Comment by NickleDave** [comment]
Hi @TomasBeuzen! Happy new year to you as well.

LGTM! 👍 The writing is very clear.

My impression of `pdm`:
- strengths:
  - uses [PEP 518](https://www.python.org/dev/peps/pep-0518/)-style metadata in pyproject.toml, like `flit`
  - does give you a `poetry` like experience
  - has a nice "convert" functionality for an existing pyproject.toml
- (possible) weaknesses:
  - goes all in on [pep 582](https://discuss.python.org/t/pep-582-python-local-packages-directory/963)
  - still is strict about upper caps on Python even -- would be nice if you could there was an `--ignore-upper-python-cap` option
  - docs are currently super sparse, I had to look at `flit`'s a lot to rewrite my `pyproject.toml`

For now I have just switched to `flit` and `venv`, will let you know if I live to regret this 🙂

**Comment by henryiii** [comment]
Here are few followup points on PDM:

* You can use Flit _and_ PDM at the same time, due to PEP 621. So you can have a build-time dependence on Flit only, and use PDM as a developer. :) PDM's backend does support VCS versioning, though.
* PDM can disable default version upper capping via a config option. Still want it to be the default. And it still forces lockfile version capping onto your python limit. (`strategy.save`)
* You can also set an option to disable PEP 582. `use_venv` or `PDM_USE_VENV`.

See https://pdm.fming.dev/configuration/

I think I've moved all my Poetry projects to PDM, due to frustration with Poetry not following standards or even standard terminology. As a result, the new poetry plugins are going to be specified as `[tool.poetry.plugins."poetry.plugin"]` :facepalm:

Docs are very slim, though, true.

**Comment by NickleDave** [comment]
Good to know, thank you @henryiii !!!
I will look at `pdm` again.
It would definitely be nice to have dev environments pinned down with lockfiles.

**Comment by TomasBeuzen** [comment]
Thanks both - very useful insights. We appreciate you taking the time to share your thoughts. I'm going to start trying out PDM myself to get a better feel for it. 

I do still feel that `poetry` is a suitable tool for introducing packaging to beginners. Despite some inconsistencies in standards, I think it provides a good mix of exposure to packaging, whilst abstracting some of the more complex details away. We recently used `poetry` and this book to teach Python software dev to a group of ~100 masters students and it went very well (except for a few students on Windows - it can still be a little tricky to properly configure `poetry` on windows. We're in the process of supporting and documenting a Docker image for Windows folks who might read the book and run into problems.) 

Anyways, I'll merge the linked PR in after another round of internal revisions 💪

**Comment by NickleDave** [comment]
:+1: totally agree `poetry` has the right level of abstraction for introducing packaging. 
That's why I keep pointing people to your book!

**Comment by henryiii** [comment]
IMO, `pdm` has exactly the same level of abstraction as `poetry`, and it uses much better standards-based terminology. It also uses much simpler dependency specification that looks like ever other tool out there, rather than custom TOML inline tables.

```toml
[tool.poetry.dependencies]
python = ">=3.6"
numpy = ">=1.13.3"
typing_extensions = { version = ">=3.7", python = "<3.8" }

sphinx = {version = "^4.0", optional = true}
sphinx_book_theme = { version = ">=0.0.40", optional = true }
sphinx_copybutton = { version = ">=0.3.1", optional = true }
pytest = { version = ">=6", optional = true }
importlib_metadata = { version = ">=1.0", optional = true, python = "<3.8" }
boost-histogram = { version = ">=1.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = ">=5.2"
importlib_metadata = {version = ">=1.0", python = "<3.8" }
boost_histogram = ">=1.0"

[tool.poetry.extras]
docs = ["sphinx", "sphinx_book_theme", "sphinx_copybutton"]
test = ["pytest", "importlib_metadata", "boost_histogram" ]
```

Vs.

```toml
[project]
requires-python = ">=3.6"
...

[project.optional-dependencies]
docs = [
  "sphinx>=4.0",
  "sphinx-book-theme>=0.0.40",
  "sphinx-copybutton>=0.3.1",
]
test = [
  "pytest>=6",
  "importlib-metadata>=1.0; python_version<'3.8'",
  "boost-histogram>=1.0",
]

# Optional
[tool.pdm.dev-dependencies]
dev = [
  "pytest>=6",
  "importlib-metadata>=1.0; python_version<'3.8'",
  "boost-histogram>=1.0",
]
```

See https://github.com/scikit-hep/uhi/pull/49/files for an example of a conversion.
